TexasInstruments/edgeai-gst-apps

- tests/process_performence_data.py
Signed-off-by: Abhay Chirania <a-chirania@ti.com>
> process_performance_data: Add feature to construct combined report

- tests/gen_performence_data.sh
Signed-off-by: Abhay Chirania <a-chirania@ti.com>
Signed-off-by: Rahul T R <r-ravikumar@ti.com>
Co-authored-by: Rahul T R <r-ravikumar@ti.com>
> test: gen_perf: Add more test cases for IMX390 (4, 6 and 8 ch)

- download_models.sh
Signed-off-by: Rahul T R <r-ravikumar@ti.com>
> models: Update download link for 8.6 RC1

- tests/gen_performance_data.sh
- tests/process_performence_data.py
Signed-off-by: Abhay Chirania <a-chirania@ti.com>
> tests: gen_performance_data: Update default OD Model

- apps_cpp/common/src/edgeai_demo_config.cpp
- apps_python/edge_ai_class.py
- scripts/optiflow/optiflow_class.py
Signed-off-by: Abhay Chirania <a-chirania@ti.com>
> edgeai-gst-apps: Align with core_number addition in dl-inferer

- configs/app_config_template.yaml
- configs/display_and_encode_example.yaml
- configs/face_detection.yaml
- configs/http_src_example.yaml
- configs/image_classification.yaml
- configs/imx390_cam_example.yaml
- configs/multi_input_multi_infer.yaml
- configs/object_detection.yaml
- configs/ov5640_sensor_example.yaml
- configs/remote_display.yaml
- configs/rpiV2_cam_example.yaml
- configs/rtsp_src_example.yaml
- configs/semantic_segmentation.yaml
- configs/shared_model_instance.yaml
- configs/single_input_multi_infer.yaml
Update configs to include perfoverlay for kmssink. Also change titles.
> configs: Update configs

- apps_cpp/common/src/edgeai_demo_config.cpp
- apps_cpp/common/src/edgeai_gst_helper.cpp
- apps_python/gst_wrapper.py
- apps_python/utils.py
- configs/app_config_template.yaml
- configs/display_and_encode_example.yaml
- configs/face_detection.yaml
- configs/gst_plugins_map.yaml
- configs/image_classification.yaml
- configs/multi_input_multi_infer.yaml
- configs/object_detection.yaml
- configs/remote_display.yaml
- configs/semantic_segmentation.yaml
- configs/shared_model_instance.yaml
- configs/single_input_multi_infer.yaml
- scripts/optiflow/config_parser.py
- scripts/optiflow/gst_wrapper.py
Add support for h264 and h265 videos. Also change
default config file to use h264 videos.
> edgeai-gst-apps: Add support for raw videos.

- scripts/optiflow/config_parser.py
- scripts/optiflow/gst_wrapper.py
kmssink use sync=true only in case of image inputs.
> optiflow: Fix issue with multifilesrc and kmssink

- init_script.sh
Since these are now handled as part of SDK
> init: Remove killing weston and setting time

- configs/imx390_cam_example.yaml
- configs/object_detection.yaml
- configs/rpiV2_cam_example.yaml
- init_script.sh
Also add EDGEAI_VERSION env variable
> configs: Update some default models.

- tests/gen_performance_data.sh
Number of C7x available for all SOC except
j784s4 is 1
> test: gen_performance_data: Bug fix

- scripts/optiflow/gst_wrapper.py
.avi video requires increased tiovxmemalloc pool-size with dmabuf import
> edgeai-gst-apps: Increase tiovxmemalloc pool-size

- scripts/optiflow/optiflow.sh
Add a script which starts optiflow pipeline
and also prints inference time using gst tracer
logs
> scripts: optiflow: Add a script to run optiflow

- scripts/setup_cameras.sh
Support hetrogeneous camera setup for imx390 and ov2312 together.
> setup_camera: Support hetrogeneous camera setup

- optiflow/config_parser.py
- optiflow/gst_wrapper.py
Use roi property for tiovxmultiscaler/tiscaler instead of using videobox
> optiflow: Use roi property for tiovxmultiscaler/tiscaler

- scripts/install_robotics_sdk.sh
- scripts/install_ti_gpio_libs.sh
install_ti_gpio_libs.sh: release-1.1.0
install_robotics_sdk.sh: REL.08.06.01
> Update the tags for GPIO libs and Robotics SDK

- apps_cpp/common/src/post_process_image_classify.cpp
- apps_python/post_process.py
Add background to text for better visibility
> post_process: classify: Add background to the text

- init_script.sh
- optiflow/gst_wrapper.py
Also revert commit f6b7a8e9c32260cbbb280f0ecd329aaeee21bff6
> init_script: Set display primary plane zpos to 0

- configs/app_config_template.yaml
- configs/display_and_encode_example.yaml
- configs/face_detection.yaml
- configs/http_src_example.yaml
- configs/image_classification.yaml
- configs/imx390_cam_example.yaml
- configs/multi_input_multi_infer.yaml
- configs/object_detection.yaml
- configs/ov5640_sensor_example.yaml
- configs/remote_display.yaml
- configs/rpiV2_cam_example.yaml
- configs/rtsp_src_example.yaml
- configs/semantic_segmentation.yaml
- configs/shared_model_instance.yaml
- configs/single_input_multi_infer.yaml
- download_models.sh
- tests/gen_performance_data.sh
- tests/test_config.yaml
Update model_zoo to include public link for
am62x.Also update config files to work across
all soc including am62x. Also update sample
video names.
> Update model_zoo link and config files.

- apps_cpp/common/src/edgeai_demo_config.cpp
- apps_python/edge_ai_class.py
- apps_python/gst_wrapper.py
- apps_python/infer_pipe.py
Python KeyboardInterrupt bug fix.
thread.join blocks the main thread hence
could not trigger KeyboardInterrupt
> apps_python: Fix issue closing with Ctrl+C

- scripts/setup_cameras.sh
Add cdns routing required with latest TI-linux-6.1.y
> setup_camera: Add cdns routing

- scripts/install_robotics_sdk.sh
- scripts/perf_stats/CMakeLists.txt
perf_stats: Updated CMakeLists.txt with header file location changes
install_robotics_sdk.sh: GIT_TAG now sets to REL.09.00.00
> perf_stats fix & install_robotics_sdk script update

- configs/app_config_template.yaml
- configs/face_detection.yaml
- configs/http_src_example.yaml
- configs/image_classification.yaml
- configs/imx390_cam_example.yaml
- configs/multi_input_multi_infer.yaml
- configs/object_detection.yaml
- configs/ov5640_sensor_example.yaml
- configs/remote_display.yaml
- configs/rpiV2_cam_example.yaml
- configs/rtsp_src_example.yaml
- configs/semantic_segmentation.yaml
- configs/shared_model_instance.yaml
- configs/single_input_multi_infer.yaml
- scripts/remote_streaming/server.js
- scripts/setup_cameras.sh
Add support for node.js based remote streaming of
jpegencoded images.
> Add support for node.js based remote streaming

- init_script.sh
This reverts commit ebaa20cb1ea6ce460062d94e021fbccb5686365f.
> Revert "init_script: Set display primary plane zpos to 0"

- docker/Dockerfile
- docker/docker_run.sh
- docker/entrypoint.sh
Also set some environment necessary variables
> docker: Update DOckerfile to pull ubuntu22.04

- optiflow/gst_wrapper.py
Bug fix where two msc is used in case
model dim is < 1/4 of original input size
> optiflow: Bug fix

- configs/keypoint_detection.yaml
- download_models.sh
Add option to download keypoint detection model.
Also add sample config file for keypoint detection. Also update face detection config file to use sample video by default.
> Keypoint detection

- scripts/install_ti_gpio_libs.sh
added branch variable to tag the repo to particular branch
> [scripts] modified install_ti_gpio.sh script

- configs/app_config_template.yaml
- optiflow/config_parser.py
- optiflow/gst_wrapper.py
- optiflow/optiflow_class.py
Add support to define model as null in config file This is useful in case pipeline needs to be constructed without model. Ex: Decode->Display usecase
> optiflow: Add support to define NO Model

- init_script.sh
> init_script: Remove creating dlr softlinks

- configs/app_config_template.yaml
- configs/imx219_cam_example.yaml
- scripts/setup_cameras.sh
Instead of "rpi", use "imx219"
> Use "imx219" name for imx219 camera.

- scripts/setup_cameras.sh
- scripts/setup_cameras_v3link.sh
In tiL6.6 kernel, following the upstream APIs for media graph, it is now required to match the formats set on every subdev and the video dev, else link validation fails and streaming will not start.
So update the scripts to set format on ticsi2rx subdev, and also the video nodes (for multi-stream scenarios).
Note: This has been tested with:
1. 1x OV5640 directly connected
2. 2x IMX219 + 1x OV2312 connected through V3Link mini fusion 
Other scenarios should work but have not been manually verified.
> scripts: Update setup_cameras script for tiL6.6

- scripts/perf_stats/README.md
> perf_stats/README: updated readme file
